imports:
    - { resource: factories.yml }
    - { resource: library_services.yml }
    - { resource: core_services.yml }

parameters:
    apiContentType: 'application/json'
    contentType: 'json'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SupportPal\ApiClient\ApiClient:
        public: true
        arguments:
            $httpClient: '@GuzzleHttp\Client'
            $decoder: '@Symfony\Component\Serializer\Encoder\JsonEncoder'
            $formatType: '%contentType%'
