imports:
    - { resource: factories.yml }
    - { resource: library_services.yml }
    - { resource: core_services.yml }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    SupportPal\ApiClient\ApiClient:
        public: true
        arguments:
            $httpClient: '@GuzzleHttp\Client'


